[env:seeed_xiao_ble]
platform = nordicnrf52
board = seeed_xiao_ble
framework = arduino
monitor_speed = 115200

lib_deps =
    seeed-studio/Seeed Arduino LSM6DS3 @ ^2.0.3
    adafruit/Adafruit Bluefruit nRF53 = https://github.com/adafruit/Adafruit_nRF52_Arduino.git